export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERR = "LOGIN_ERR"

export const SIGNUP_REQ = "SIGNUP_REQ"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERR = "SIGNUP_ERR"

export const LIST_REQ = "LIST_REQ"
export const LIST_SUCCESS = "LIST_SUCCESS"
export const LIST_ERR = "LIST_ERR"

export const DEL_LIST_REQ = "DEL_LIST_REQ"
export const DEL_LIST_SUCCESS = "DEL_LIST_SUCCESS"
export const DEL_LIST_ERR = "DEL_LIST_ERR"

export const ADD_LIST_REQ = "ADD_LIST_REQ"
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS"
export const ADD_LIST_ERR = "ADD_LIST_ERR"

export const DEL_OPTION_LIST_REQ = "DEL_OPTION_LIST_REQ"
export const DEL_OPTION_LIST_SUCCESS = "DEL_OPTION_LIST_SUCCESS"
export const DEL_OPTION_LIST_ERR = "DEL_OPTION_LIST_ERR"

export const ADD_OPTION_LIST_REQ = "ADD_OPTION_LIST_REQ"
export const ADD_OPTION_LIST_SUCCESS = "ADD_OPTION_LIST_SUCCESS"
export const ADD_OPTION_LIST_ERR = "ADD_OPTION_LIST_ERR"

export const VOTE_REQ = "VOTE_REQ"
export const VOTE_SUCCESS = "VOTE_SUCCESS"
export const VOTE_ERR = "VOTE_ERR"

export const TITLE_REQ = "TITLE_REQ"
export const TITLE_SUCCESS = "TITLE_SUCCESS"
export const TITLE_ERR = "TITLE_ERR"